server:
 host: data have been erased

headers:
 Content-Type: application/json

database:
 host: data have been erased
 user: data have been erased
 password: '123456'
 port: 3306
 database: data have been erased


log_conf:
  name: "python_api_automation"
  level: "INFO"
  formatter: "%(asctime)s-%(levelname)s:%(name)s-%(filename)s-%(created)s -%(lineno)s:::%(message)s"